### ISSUE TITLE
Idő mérés?

### ISSUE THREAD

**Issue by 963HU** [rolandfarkasCOM/cf-7-honeypot#1]
Szia, bonyolult mérni mennyi idő alatt adja be az űrlapot a felhasználó? Csak egy tipp másik plugintól: "spam bots using the time it takes to submit the form under the idea that bots submit forms faster than people. The value is set to 4 seconds by default,"

**Comment by rolandfarkasCOM** [comment]
Szia, hozzá adtam egy idő mèrő funkciót, ha van valami hiba vele nyugodtan jelezd itt.
